import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/commons/layout/header';
import { BookProvider } from '@/hooks/useBookContext';
import MenuLink from '@/components/ui/menuLink';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased  md:h-screen h-full`}>
                <Header />
                <main className=" w-full h-[calc(100%-100px)] h-full">
                    <BookProvider>{children}</BookProvider>
                </main>

                <div className="absolute bottom-0 right-0 md:w-[500px] md:h-[500px] w-[300px] h-[300px] rounded-full bg-[#EBB400] blur-xl opacity-10 z-[-1]"></div>
            </body>
        </html>
    );
}
